Repository Morning-Study-Coding/codingTest, pull requests merged in 2025-06, with the labels that each got.

#37 day18: 미들러
  src/main/java/org/example/jr/day18/BJN_17503.java
  src/main/java/org/example/jr/day18/BJN_17503_Binary.java
Labels: Midder, FAIL

#36 day 18 미들러 - 맥주축제
  src/main/java/org/example/ne/day18/middler/B17503_맥주축제.java
  src/main/java/org/example/ne/day19/middler/B1946_신입사원.java
Labels: Midder, SUCCESS, FAIL

#39 day20 미들러 - 최소 회의실 개수
  src/main/java/org/example/ne/day20/middler/B19598_최소_회의실_개수.java
Labels: Midder, SUCCESS

#40 day20: 그리디
  src/main/java/org/example/jr/day20/BJN_19598.java
Labels: Midder, SUCCESS
